"""Port Ferry PortFerry User Country

Revision ID: 00b87a3d94a3
Revises:
Create Date: 2023-09-29 17:36:49.704308

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "00b87a3d94a3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("abbreviated_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("last_request", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ferries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("time_departure", sa.String(length=30), nullable=True),
        sa.Column("time_arrival", sa.String(length=30), nullable=True),
        sa.Column("port_departure_id", sa.Integer(), nullable=True),
        sa.Column("port_arrival_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["port_arrival_id"],
            ["ports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["port_departure_id"],
            ["ports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "port_ferry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("port_id", sa.Integer(), nullable=True),
        sa.Column("ferry_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ferry_id"],
            ["ferries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["port_id"],
            ["ports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("port_ferry")
    op.drop_table("ferries")
    op.drop_table("users")
    op.drop_table("ports")
    op.drop_table("countries")
    # ### end Alembic commands ###
