"""add port dependency

Revision ID: 4c3cbbdcddd4
Revises: 00b87a3d94a3
Create Date: 2023-09-29 17:41:03.655173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c3cbbdcddd4'
down_revision = '00b87a3d94a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ports', sa.Column('country_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ports', 'countries', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ports', type_='foreignkey')
    op.drop_column('ports', 'country_id')
    # ### end Alembic commands ###
