"""add owner ferries relations

Revision ID: 8b9d487d1814
Revises: ed9b9f4777d5
Create Date: 2023-10-10 10:09:25.761723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9d487d1814'
down_revision = 'ed9b9f4777d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ferries', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ferries', 'owners', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ferries', type_='foreignkey')
    op.drop_column('ferries', 'owner_id')
    op.drop_table('owners')
    # ### end Alembic commands ###
