"""add language enum

Revision ID: ed9b9f4777d5
Revises: 4c3cbbdcddd4
Create Date: 2023-10-04 21:33:26.102176

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ed9b9f4777d5"
down_revision = "4c3cbbdcddd4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE languages AS ENUM ('ENGLISH', 'UKRAINIAN', 'POLISH')")

    op.add_column(
        "users", sa.Column("language", sa.Enum("ENGLISH", "UKRAINIAN", "POLISH", name="languages"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS languages")

    op.drop_column("users", "language")
    # ### end Alembic commands ###
